//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentSign.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentSign.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreateDocument_AnchorOption_Description {
            get {
                return ResourceManager.GetString("CreateDocument_AnchorOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnchorOption.
        /// </summary>
        public static string CreateDocument_AnchorOption_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_AnchorOption_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Document with Signature Details.
        /// </summary>
        public static string CreateDocument_Description {
            get {
                return ResourceManager.GetString("CreateDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Document.
        /// </summary>
        public static string CreateDocument_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Output.
        /// </summary>
        public static string CreateDocument_Document_Description {
            get {
                return ResourceManager.GetString("CreateDocument_Document_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string CreateDocument_Document_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_Document_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated DocumentId .
        /// </summary>
        public static string CreateDocument_DocumentId_Description {
            get {
                return ResourceManager.GetString("CreateDocument_DocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentId.
        /// </summary>
        public static string CreateDocument_DocumentId_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_DocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full File Path to Document.
        /// </summary>
        public static string CreateDocument_DocumentPath_Description {
            get {
                return ResourceManager.GetString("CreateDocument_DocumentPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentPath.
        /// </summary>
        public static string CreateDocument_DocumentPath_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_DocumentPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page of Signature in Document.
        /// </summary>
        public static string CreateDocument_PageNumber_Description {
            get {
                return ResourceManager.GetString("CreateDocument_PageNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageNumber.
        /// </summary>
        public static string CreateDocument_PageNumber_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_PageNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Text for Signature.
        /// </summary>
        public static string CreateDocument_SignatureAnchor_Description {
            get {
                return ResourceManager.GetString("CreateDocument_SignatureAnchor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureAnchor.
        /// </summary>
        public static string CreateDocument_SignatureAnchor_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_SignatureAnchor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset for Signature (pixels).
        /// </summary>
        public static string CreateDocument_XOffset_Description {
            get {
                return ResourceManager.GetString("CreateDocument_XOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOffset.
        /// </summary>
        public static string CreateDocument_XOffset_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_XOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset for Signature (pixels).
        /// </summary>
        public static string CreateDocument_YOffset_Description {
            get {
                return ResourceManager.GetString("CreateDocument_YOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOffset.
        /// </summary>
        public static string CreateDocument_YOffset_DisplayName {
            get {
                return ResourceManager.GetString("CreateDocument_YOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Recipient.
        /// </summary>
        public static string CreateRecipient_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Recipient.
        /// </summary>
        public static string CreateRecipient_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentId.
        /// </summary>
        public static string CreateRecipient_DocumentId_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_DocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentId.
        /// </summary>
        public static string CreateRecipient_DocumentId_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_DocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Email Address of Recipient.
        /// </summary>
        public static string CreateRecipient_EmailAddress_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_EmailAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress.
        /// </summary>
        public static string CreateRecipient_EmailAddress_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_EmailAddress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full legal Name of Recipient.
        /// </summary>
        public static string CreateRecipient_FullName_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_FullName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string CreateRecipient_FullName_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_FullName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Output Object.
        /// </summary>
        public static string CreateRecipient_Recipient_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_Recipient_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string CreateRecipient_Recipient_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_Recipient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreateRecipient_Role_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string CreateRecipient_Role_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_Role_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreateRecipient_RoutingOrder_Description {
            get {
                return ResourceManager.GetString("CreateRecipient_RoutingOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutingOrder.
        /// </summary>
        public static string CreateRecipient_RoutingOrder_DisplayName {
            get {
                return ResourceManager.GetString("CreateRecipient_RoutingOrder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Envelope with Recipients and Documents for Signature.
        /// </summary>
        public static string DefineEnvelope_Description {
            get {
                return ResourceManager.GetString("DefineEnvelope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Envelope.
        /// </summary>
        public static string DefineEnvelope_DisplayName {
            get {
                return ResourceManager.GetString("DefineEnvelope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single or Multiple Document Objects.
        /// </summary>
        public static string DefineEnvelope_Documents_Description {
            get {
                return ResourceManager.GetString("DefineEnvelope_Documents_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DefineEnvelope_Documents_DisplayName {
            get {
                return ResourceManager.GetString("DefineEnvelope_Documents_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Doucments and Recipients to Envelope.
        /// </summary>
        public static string DefineEnvelope_Envelope_Description {
            get {
                return ResourceManager.GetString("DefineEnvelope_Envelope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope.
        /// </summary>
        public static string DefineEnvelope_Envelope_DisplayName {
            get {
                return ResourceManager.GetString("DefineEnvelope_Envelope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singe or Multiple Recipient Objects.
        /// </summary>
        public static string DefineEnvelope_Recipients_Description {
            get {
                return ResourceManager.GetString("DefineEnvelope_Recipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string DefineEnvelope_Recipients_DisplayName {
            get {
                return ResourceManager.GetString("DefineEnvelope_Recipients_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all Documents that are included in Envelope.
        /// </summary>
        public static string DownloadEnvelopeDocuments_Description {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Envelope Documents.
        /// </summary>
        public static string DownloadEnvelopeDocuments_DisplayName {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder.
        /// </summary>
        public static string DownloadEnvelopeDocuments_DownloadPath_Description {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_DownloadPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Path.
        /// </summary>
        public static string DownloadEnvelopeDocuments_DownloadPath_DisplayName {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_DownloadPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope ID.
        /// </summary>
        public static string DownloadEnvelopeDocuments_EnvelopeID_Description {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_EnvelopeID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope ID.
        /// </summary>
        public static string DownloadEnvelopeDocuments_EnvelopeID_DisplayName {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_EnvelopeID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Documents by Status, Check all Items that need to be included .
        /// </summary>
        public static string DownloadEnvelopeDocuments_EnvelopeStatusFilter_Description {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_EnvelopeStatusFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope Status Filter.
        /// </summary>
        public static string DownloadEnvelopeDocuments_EnvelopeStatusFilter_DisplayName {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_EnvelopeStatusFilter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of downloaded Files.
        /// </summary>
        public static string DownloadEnvelopeDocuments_Files_Description {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_Files_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string DownloadEnvelopeDocuments_Files_DisplayName {
            get {
                return ResourceManager.GetString("DownloadEnvelopeDocuments_Files_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_CreatedDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_CreatedDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_CreatedDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_CreatedDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_DeclinedDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeclinedDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeclinedDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_DeclinedDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeclinedDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_DeletedDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeletedDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_DeletedDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeletedDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_DeliveredDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeliveredDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveredDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_DeliveredDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DeliveredDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get specific Information of Envelope.
        /// </summary>
        public static string GetEnvelopeInformation_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnvelopeInformation.
        /// </summary>
        public static string GetEnvelopeInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Document IDs attached to this Envelope.
        /// </summary>
        public static string GetEnvelopeInformation_DocumentIds_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DocumentIds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentIds.
        /// </summary>
        public static string GetEnvelopeInformation_DocumentIds_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_DocumentIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeID.
        /// </summary>
        public static string GetEnvelopeInformation_EnvelopeId_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_EnvelopeId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeId.
        /// </summary>
        public static string GetEnvelopeInformation_EnvelopeId_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_EnvelopeId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string GetEnvelopeInformation_EnvelopeStatus_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_EnvelopeStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeStatus.
        /// </summary>
        public static string GetEnvelopeInformation_EnvelopeStatus_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_EnvelopeStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_ExpireDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_ExpireDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpireDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_ExpireDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_ExpireDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope Json Data.
        /// </summary>
        public static string GetEnvelopeInformation_JsonData_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_JsonData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonData.
        /// </summary>
        public static string GetEnvelopeInformation_JsonData_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_JsonData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Recipients and their Role in this Envelope.
        /// </summary>
        public static string GetEnvelopeInformation_Recpients_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_Recpients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recpients.
        /// </summary>
        public static string GetEnvelopeInformation_Recpients_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_Recpients_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_SentDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_SentDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SentDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_SentDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_SentDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp Statuschange.
        /// </summary>
        public static string GetEnvelopeInformation_StatusChangedDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_StatusChangedDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusChangedDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_StatusChangedDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_StatusChangedDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_VoidedDateTime_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_VoidedDateTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoidedDateTime.
        /// </summary>
        public static string GetEnvelopeInformation_VoidedDateTime_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_VoidedDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetEnvelopeInformation_VoidedReason_Description {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_VoidedReason_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoidedReason.
        /// </summary>
        public static string GetEnvelopeInformation_VoidedReason_DisplayName {
            get {
                return ResourceManager.GetString("GetEnvelopeInformation_VoidedReason_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax: custom_envelope_field_name=desired_value.
        /// </summary>
        public static string ListEnvelopes_CustomField_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_CustomField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomField.
        /// </summary>
        public static string ListEnvelopes_CustomField_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_CustomField_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a list of envelopes that match your request. A large set of optional filters let you filter by date, by envelope ID, or by status codes..
        /// </summary>
        public static string ListEnvelopes_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListEnvelopes.
        /// </summary>
        public static string ListEnvelopes_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListEnvelopes_EnvelopeIDs_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_EnvelopeIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeIDs.
        /// </summary>
        public static string ListEnvelopes_EnvelopeIDs_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_EnvelopeIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Folder Guids.
        /// </summary>
        public static string ListEnvelopes_FolderIDs_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_FolderIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderIDs.
        /// </summary>
        public static string ListEnvelopes_FolderIDs_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_FolderIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY-DD-MM.
        /// </summary>
        public static string ListEnvelopes_FromDate_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_FromDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDate.
        /// </summary>
        public static string ListEnvelopes_FromDate_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_FromDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListEnvelopes_FromToStatus_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_FromToStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromToStatus.
        /// </summary>
        public static string ListEnvelopes_FromToStatus_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_FromToStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies additional information to return about the envelopes..
        /// </summary>
        public static string ListEnvelopes_Include_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_Include_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string ListEnvelopes_Include_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_Include_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched EnvelopeIDs.
        /// </summary>
        public static string ListEnvelopes_MatchingEnvelopes_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_MatchingEnvelopes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchtingEnvelopeIDs.
        /// </summary>
        public static string ListEnvelopes_MatchingEnvelopes_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_MatchingEnvelopes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit max Number of Results.
        /// </summary>
        public static string ListEnvelopes_MaxResults_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_MaxResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxResults.
        /// </summary>
        public static string ListEnvelopes_MaxResults_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_MaxResults_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text search to filter Results.
        /// </summary>
        public static string ListEnvelopes_SearchText_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_SearchText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchText.
        /// </summary>
        public static string ListEnvelopes_SearchText_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_SearchText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY-DD-MM.
        /// </summary>
        public static string ListEnvelopes_ToDate_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_ToDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDate.
        /// </summary>
        public static string ListEnvelopes_ToDate_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_ToDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListEnvelopes_TransactionIDs_Description {
            get {
                return ResourceManager.GetString("ListEnvelopes_TransactionIDs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionIDs.
        /// </summary>
        public static string ListEnvelopes_TransactionIDs_DisplayName {
            get {
                return ResourceManager.GetString("ListEnvelopes_TransactionIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Envelope and Send.
        /// </summary>
        public static string SendEnvelope_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Envelope.
        /// </summary>
        public static string SendEnvelope_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject Text.
        /// </summary>
        public static string SendEnvelope_EmailSubject_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_EmailSubject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSubject.
        /// </summary>
        public static string SendEnvelope_EmailSubject_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_EmailSubject_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Envelope .
        /// </summary>
        public static string SendEnvelope_Envelope_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_Envelope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope.
        /// </summary>
        public static string SendEnvelope_Envelope_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_Envelope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of Sent Envelope.
        /// </summary>
        public static string SendEnvelope_EnvelopeID_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_EnvelopeID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeID.
        /// </summary>
        public static string SendEnvelope_EnvelopeID_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_EnvelopeID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of Envelope.
        /// </summary>
        public static string SendEnvelope_EnvelopeStatus_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_EnvelopeStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvelopeStatus.
        /// </summary>
        public static string SendEnvelope_EnvelopeStatus_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_EnvelopeStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendEnvelope_Status_Description {
            get {
                return ResourceManager.GetString("SendEnvelope_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SendEnvelope_Status_DisplayName {
            get {
                return ResourceManager.GetString("SendEnvelope_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI of the authentication service instance to be used..
        /// </summary>
        public static string SignScope_AuthenticationServer_Description {
            get {
                return ResourceManager.GetString("SignScope_AuthenticationServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationServer.
        /// </summary>
        public static string SignScope_AuthenticationServer_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_AuthenticationServer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integration key (also known as client ID) of the application.
        /// </summary>
        public static string SignScope_ClientD_Description {
            get {
                return ResourceManager.GetString("SignScope_ClientD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientD.
        /// </summary>
        public static string SignScope_ClientD_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_ClientD_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope for Activities to interact with DocuSign eSign Services.
        /// </summary>
        public static string SignScope_Description {
            get {
                return ResourceManager.GetString("SignScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Scope.
        /// </summary>
        public static string SignScope_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Private Key.
        /// </summary>
        public static string SignScope_PrivateKey_Description {
            get {
                return ResourceManager.GetString("SignScope_PrivateKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateKey.
        /// </summary>
        public static string SignScope_PrivateKey_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_PrivateKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SignScope_RedirectUri_Description {
            get {
                return ResourceManager.GetString("SignScope_RedirectUri_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectUri.
        /// </summary>
        public static string SignScope_RedirectUri_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_RedirectUri_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SignScope_TargetAccountID_Description {
            get {
                return ResourceManager.GetString("SignScope_TargetAccountID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetAccountID.
        /// </summary>
        public static string SignScope_TargetAccountID_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_TargetAccountID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID of the user to be impersonated..
        /// </summary>
        public static string SignScope_UserID_Description {
            get {
                return ResourceManager.GetString("SignScope_UserID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string SignScope_UserID_DisplayName {
            get {
                return ResourceManager.GetString("SignScope_UserID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
